apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app:  flask-test-app
    name: acretest
spec:
    replicas: 2
    selector:
        matchLabels:
            app: flask-test-app
    template:
        metadata:
            labels:
                app: flask-test-app
        spec:
            containers:
            - image:  docker.io/espirado/app-oneacre:appv2
              imagePullPolicy: IfNotPresent
              name: flask-test-app